### PR TITLE
fix: filter out props keys that are not defined in atom api

### LINKED ISSUE #1758: Residual left after prop is deleted
## Current Behavior

although a prop is deleted from the atom's api, the elements of that prop keep having that prop and its last value before deletion.

## Expected Behavior

No residual should be left.

## Steps to Reproduce

https://user-images.githubusercontent.com/51242349/187069078-58a993be-74c7-4582-a51e-60daf0ffd3dc.mp4

### PR DESCRIPTION
**Pull request by melhamin**
## Description (Optional)

This PR includes a frontend solution for removing props that are left over in elements props after deleting it from atom's api. Replaces existing solution that updates element element props after the prop is deleted from atom's api.

- [x] Move filtering out logic to the `Prop` model
- [x] Fix props not filtered when navigating back to the `Builder` tab after deleting prop from Atom API (filtered after page refresh)

## Related Issue(s)

Fixes #1758

### CODE REVIEW

File: libs/frontend/domain/renderer/src/element/ElementWrapper.ts [hunk 1]
```diff
@@ -117,4 +126,19 @@ export const ElementWrapper = observer<ElementWrapperProps>(
   },
 )
 
+// Removes keys from element props that are not defined in the atom API
+// This is to prevent rendering props left over after deleting it from the atom API
+const removeLeftOverPropsNotDefinedInAtomAPI = (element: IElement) => {
+  if (element.atom?.current.api.current) {
```
Comment (webberwang) [inline libs/frontend/domain/renderer/src/element/ElementWrapper.ts:132]: unit specs failing, try `maybeCurrent`

File: libs/frontend/domain/renderer/src/element/ElementWrapper.ts [hunk 2]
```diff
@@ -117,4 +126,19 @@ export const ElementWrapper = observer<ElementWrapperProps>(
...
+    const atomApiInterface = element.atom.current.api.current as IInterfaceType
+    const atomApiPropsMap = atomApiInterface.fields.items
+    const atomApiPropsKeys = values(atomApiPropsMap).map((field) => field.key)
+    const elementPropsMap = element.props?.data.data
+    const elementPropsKeys = keys(elementPropsMap)
+    const keysToOmit = difference(elementPropsKeys, atomApiPropsKeys)
+
+    keysToOmit.forEach((key) => element.props?.delete(key))
```
Comment (webberwang) [inline libs/frontend/domain/renderer/src/element/ElementWrapper.ts:140]: I'm thinking the prop model should have a reference to an interface type? This way we can move all the logic there

That would make sense domain wise, since dats shape is dependent on the interface

**Review by webberwang — CHANGES_REQUESTED** [review]

File: libs/frontend/domain/renderer/src/element/ElementWrapper.ts (hunk 2 above)
Comment (melhamin) [reply libs/frontend/domain/renderer/src/element/ElementWrapper.ts:140]: Yeah it makes sense, if we have the interface type in prop model. Will try that

File: libs/frontend/domain/prop/src/store/prop.model.ts [hunk 3]
```diff
@@ -1,9 +1,13 @@
 import type {
+  IInterfaceType,
   IProp,
   IPropData,
   IPropDTO,
 } from '@codelab/frontend/abstract/core'
+import { Maybe } from '@codelab/shared/abstract/types'
 import { mergeProps, propSafeStringify } from '@codelab/shared/utils'
+// eslint-disable-next-line lodash/import-scope
+import { difference, keys, values } from 'lodash'
```
Comment (webberwang) [inline libs/frontend/domain/prop/src/store/prop.model.ts:10]: here we do want to import using `lodash/*` etc

File: libs/frontend/domain/renderer/src/element/ElementWrapper.ts [hunk 4]
```diff
@@ -3,6 +3,7 @@ import { CUSTOM_TEXT_PROP_KEY } from '@codelab/frontend/domain/element'
 import { Nullish } from '@codelab/shared/abstract/types'
 import { mergeProps } from '@codelab/shared/utils'
 import { jsx } from '@emotion/react'
+// eslint-disable-next-line lodash/import-scope
```
Comment (webberwang) [inline libs/frontend/domain/renderer/src/element/ElementWrapper.ts:6]: remove this

File: libs/frontend/domain/prop/src/store/prop.model.ts [hunk 5]
```diff
@@ -14,23 +18,40 @@ import {
...
   get values() {
+    // Filter out keys inside props that are not defined in the atom API
+    // This is to prevent rendering props left over after deleting them from the atom API
+    if (this.api) {
+      const apiPropsMap = this.api.current.fields.items
+      const apiPropsKeys = values(apiPropsMap).map((field) => field.key)
+      const currentPropsKeys = keys(this.data.data)
+      const keysToOmit = difference(currentPropsKeys, apiPropsKeys)
+
+      keysToOmit.forEach((key) => this.delete(key))
```
Comment (webberwang) [inline libs/frontend/domain/prop/src/store/prop.model.ts:52]: add https://typescript-eslint.io/rules/no-dynamic-delete/ to root eslint, let's use a map reduce strategy

https://www.npmjs.com/package/omit-deep-lodash

Mouse_Highlight_Overlay

**Review by webberwang — CHANGES_REQUESTED** [review]

File: libs/frontend/domain/prop/src/store/prop.model.ts (hunk 5 above)
Comment (melhamin) [reply libs/frontend/domain/prop/src/store/prop.model.ts:52]: Why do we need to add no-dynamic-delete rule?

Comment (webberwang) [reply libs/frontend/domain/prop/src/store/prop.model.ts:52]: don't think it's good practice as it's mutable
no-dynamic-delete___TypeScript_ESLint

Comment (melhamin) [reply libs/frontend/domain/prop/src/store/prop.model.ts:52]: We are not using dynamic delete here

Comment (webberwang) [reply libs/frontend/domain/prop/src/store/prop.model.ts:52]: oh nevermind, also it's already added

Comment (melhamin) [reply libs/frontend/domain/prop/src/store/prop.model.ts:52]: Should still use https://www.npmjs.com/package/omit-deep-lodash? both would be the same, just one extra package dependency.

Comment (webberwang) [reply libs/frontend/domain/prop/src/store/prop.model.ts:52]: Could try this https://stackoverflow.com/a/53398058/2159920

Comment (melhamin) [reply libs/frontend/domain/prop/src/store/prop.model.ts]: I want to use [omitBy](https://lodash.com/docs/4.17.15#omitBy) instead. Seem better and cleaner solution than omit.
